#!/usr/bin/env python

import sys, os

from urllib import urlopen
import csv
import json


#> catGetDatasetInfo v7-4-3

cmsswpath=os.environ.get('SRT_CMSSW_BASE_SCRAMRTDEL')+"/src/CATTools/CatAnalyzer/data/dataset/"
json_ = open(cmsswpath+"dataset.json")
dataset = json.load(json_)
DoubleRun2015=['DoubleEG_Run2015C', 'DoubleEG_Run2015D', 'DoubleMuon_Run2015C', 'DoubleMuon_Run2015D', 'MuonEG_Run2015C', 'MuonEG_Run2015D']
TTbarMC=['TTJets_MG5', 'TTJets_aMC', 'TTJets_scaleup', 'TTJets_scaledown', 'TT_powheg', 'TT_powheg_scaledown', 'TT_powheg_scaleup', 'TT_amcatnlo-herwigpp', 'TT_powheg-herwigpp', 'TT_powheg_pythia6', 'TTG']
BkgMC=['WJets', 'SingleTbar_tW', 'SingleTop_tW', 'WW', 'WZ', 'ZZ', 'ttWJetsToQQ', 'ttWJetsToLNu', 'ttZToLLNuNu', 'ttZToQQ']
DYMC=['DYJets', 'DYJets_10to50', 'DYJets_MG', 'DYJets_MG_5to50']
ttV=['ttWJetsToQQ', 'ttWJetsToLNu', 'ttZToLLNuNu', 'ttZToQQ']
#etc=['ttWJetsToLNu','ttZToLLNuNu']
etc=['MuonEG_Run2015D','DYJets']
MC = TTbarMC+BkgMC+DYMC
LL = DoubleRun2015+TTbarMC+BkgMC+DYMC

iii=0
args=["--jobName","--fileList","--maxFiles","--cfg","--transferDest","--args","--customise customise_cff.py"]
for aa in dataset:
 isLL    = aa['name'] in LL
 isTTbar = aa['name'] in TTbarMC 
 isTTV = aa['name'] in ttV
 isMC = aa['name'] in MC
 isDATA = aa['name'] in DoubleRun2015
 isEtc = aa['name'] in etc
 if ( isMC ) :
   #ddd = "create-batch -n "
   ddd = "create-batch "
   ddd+= args[0]+" "+aa['name']+" "
   ddd+= args[1]+" "+cmsswpath+"/dataset_"+aa['name']+".txt "
   ddd+= args[2]+" 20 "

   fff = "/store/user/youngjo/Cattools/v7-6-5v1/"+aa['name']+"v1"
   ddd+= args[3]+" ../run_TtbarBbbarDiLeptonAnalyzer_cfg.py "
   ddd+= args[4]+" "+fff+" "

   #eee="srmmkdir srm://cms-se.sdfarm.kr:8443/srm/v2/server?SFN=/xrootd"+fff
   #os.system(eee)
   print ddd
   os.system(ddd)
   iii=iii+1

