#!/usr/bin/env python

import sys, os

if len(sys.argv) < 2:
    print sys.argv[0], "PROD_VERSION"
    print "Default PROD_VERSION = v7-4-2"
    sys.argv.append("v7-4-2")

era = sys.argv[1]

from CATTools.CatAnalyzer.libxrd import *

prefix = "/store/group/CAT"

dsLists = ["RD/prod_Run2015-25ns-RunIISpring15MiniAODv2.txt", "MC/prod_MCRUN2_74_V9-25ns-RunIISpring15MiniAODv2.txt", "MC/prod_MCRUN2_74_V9-25ns-RunIISpring15MiniAODv2-qcd.txt"]
for dsList in dsLists:
    for d in open("%s/src/CATTools/CatProducer/prod/%s" % (os.environ["CMSSW_BASE"], dsList)).readlines():
        d = d.strip()
        if len(d) == 0 or d[0] == '#': continue

        d = d.split('/')
        if len(d) < 4: continue

        pdName, sdName = d[1], d[2]

        path = "%s/%s/%s_%s" % (prefix, pdName, era, sdName)

        print '-'*40
        print pdName
        for ll in listxrd(path)[0]: print ll
print '-'*40
