#!/usr/bin/env python

from ROOT import *

f = TFile("egammaEffi.txt_SF2D.root")
h = f.Get("EGamma_SF2D")

nbinsX = h.GetNbinsX()
nbinsY = h.GetNbinsY()

eta_bins = [h.GetXaxis().GetBinLowEdge(i) for i in range(1, nbinsX+2)]
pt_bins  = [h.GetYaxis().GetBinLowEdge(i) for i in range(1, nbinsY+2)]

values = []
errors = []
for i in range(1, nbinsX+1):
    for j in range(1, nbinsY+1):
        val, err = h.GetBinContent(i,j), h.GetBinError(i,j)
        values.append(val)
        errors.append(err)

pt_bins_str = ",".join(["%f" % x for x in pt_bins])
eta_bins_str = ",".join(["%f" % x for x in eta_bins])
values_str, errors_str = "", ""
for j in range(len(eta_bins)-1):
    for i in range(len(pt_bins)-1):
        print i, j
        values_str += "%f" % values[i+j*(len(pt_bins)-1)] + ", "
        errors_str += "%f" % errors[i+j*(len(pt_bins)-1)] + ", "
    values_str += "\n        "
    errors_str += "\n        "

print """cms.PSet(
    pt_bins = cms.vdouble(%s),
    eta_bins = cms.vdouble(%s),
    values = cms.vdouble(%s),
    errors = cms.vdouble(%s),
)""" % (pt_bins_str, eta_bins_str, values_str, errors_str)
