#!/usr/bin/env python

from math import *
import sys

# Documentation found from https://twiki.cern.ch/twiki/bin/view/CMS/ElectronScaleFactorsRun2#Sharing_of_results_in_e_gamma_PO
# Most recent presentation https://indico.cern.ch/event/491528/contribution/2/attachments/1231399/1805319/CutBasedId_EGM_19Feb.pdf
# Cut based ID for 76X : https://arun-afs.web.cern.ch/arun-afs/Fits_Data_ID_76X_AbsEta/CutBasedID_MediumWP_76X_18Feb.txt
# Cut based ID for 74X : https://arun-afs.web.cern.ch/arun-afs/Final_Fits_Data_74X/CutBasedID_MediumWP_fromTemplates_withSyst_Final.txt

cutName = "CutBasedID_MediumWP"
fin = sys.argv[1]

ptbins = []
etabins = []
values, errors = {}, {}

for line in open(fin).readlines():
    vals = [float(x) for x in line.strip().split()]
    if len(vals) < 15: continue

    # etaMin etaMax ptMin ptMax
    eta1, eta2, pt1, pt2 = vals[:4]
    # effData statErrData effMC
    effRD, errRD, effMC, errMC = vals[4:8]
    # statErrMC effAltBkgModel effAltSigModel effAltMCSignal effAltTagSel effPUup effPUdown effAltFitRange 
    systs = [x-effMC for x in vals[8:13]+[vals[-1]] if x >= 0]

    sf, err = 1., 0
    if effMC > 0 and effRD > 0:
        sf = effRD/effMC
        err2 = (errRD/effRD)**2 + (errMC/effMC)**2
        for e in systs: err2 += (e/effRD)**2 + (e/effMC)**2
        err = sf*sqrt(err2)
  
    ptbins.append(pt1)
    ptbins.append(pt2)
    etabins.append(eta1)
    etabins.append(eta2)

    values[(pt1, eta1)] = sf
    errors[(pt1, eta1)] = err

ptbins = sorted(list(set(ptbins)))
etabins = sorted(list(set(etabins)))

print "==== SF for ID ===="
print """cms.PSet(
    # Values of "%s"
    pt_bins = cms.vdouble(%s),
    eta_bins = cms.vdouble(%s),""" % (cutName,
       (", ".join(["%g" % x for x in ptbins])),
       (", ".join(["%g" % x for x in etabins])))
print "    values = cms.vdouble("
for eta in etabins[:-1]:
    print "       ",
    for pt in ptbins[:-1]:
        print "%g," % values[(pt, eta)],
    print ""
print """    ),
    errors = cms.vdouble("""
for eta in etabins[:-1]:
    print "       ",
    for pt in ptbins[:-1]:
        print "%g," % (errors[(pt, eta)]),
    print ""
print"""    ),
)"""

