#!/usr/bin/env python

from math import *

# Documentation found from https://twiki.cern.ch/twiki/bin/viewauth/CMS/HWW2015TriggerResults#Electrons_Tables_or_text_files_f
#    First two columns are Eta range.
#    Next 2 columns are PT range.
#    Column 5 & 6 shows the efficiency in data and statistical error.
#    Column 7 & 8 shows the efficiency in MC and statistical error.
#    Column 9 shows the systematics uncertainty because of changing signal PDF.
#    Column 10 shows the systematics uncertainty because of changing background PDF.
#    Column 11 - systematics after changing the fit range.
#    Column 12 - systematics because of NLO and LO MC sample.
#    Last two columns will be systematics because of Tag selection and PU reweighing. But their effect will be really small. 

cutName = "CutBasedID_MediumWP"
fin = "/afs/cern.ch/work/a/arun/public/forEGM/CutBased_textFiles_withSyst/%s_fromTemplates_withSyst_v1.txt" % cutName

ptbins = []
etabins = []
values, errors = {}, {}

for line in open(fin).readlines():
    vals = [float(x) for x in line.strip().split()]
    if len(vals) < 12: continue

    eta1, eta2, pt1, pt2 = vals[:4]
    effRD, errRD, effMC, errMC = vals[4:8]
    systs = vals[8:]

    sf, err = 1., 0
    if effMC > 0 and effRD > 0:
        sf = effRD/effMC
        err2 = (errRD/effRD)**2 + (errMC/effMC)**2
        for e in systs:
            if e > 0: err2 += (e/effRD)**2 + (e/effMC)**2
        err = sf*sqrt(err2)
  
    ptbins.append(pt1)
    ptbins.append(pt2)
    etabins.append(eta1)
    etabins.append(eta2)

    values[(pt1, eta1)] = sf
    errors[(pt1, eta1)] = err

ptbins = sorted(list(set(ptbins)))
etabins = sorted(list(set(etabins)))

print "==== SF for ID ===="
print """cms.PSet(
    # Values of "%s"
    pt_bins = cms.vdouble(%s),
    eta_bins = cms.vdouble(%s),""" % (cutName,
       (", ".join(["%g" % x for x in ptbins])),
       (", ".join(["%g" % x for x in etabins])))
print "    values = cms.vdouble("
for eta in etabins[:-1]:
    print "       ",
    for pt in ptbins[:-1]:
        print "%g," % values[(pt, eta)],
    print ""
print """    ),
    errors = cms.vdouble("""
for eta in etabins[:-1]:
    print "       ",
    for pt in ptbins[:-1]:
        print "%g," % (errors[(pt, eta)]),
    print ""
print"""    ),
)"""

