#!/usr/bin/env python

import sys, os

import subprocess
if subprocess.call("type xrdls", shell=True, 
        stdout=subprocess.PIPE, stderr=subprocess.PIPE) != 0:
    print "Error: Need xrdls from hep-tools"
    sys.exit()

cmd = "xrdls %s"
ds = []
while True:
    l = raw_input("samples: ").strip()
    if len(l) == 0: break

    fl = list(set(subprocess.check_output(cmd % l, shell=True).strip().split()))
    fl = [os.path.basename(ff) for ff in fl if ff.endswith('.root')]
    fl.sort()

    ds.append({'path':os.path.dirname(ff), 'files':fl})

import json
f = open("samples.json", "w")
print>>f, json.dumps(ds)

