#!/usr/bin/env python

import sys, os
if len(sys.argv) < 2:
    print "Usage: makeFileList SAMPLE_KEY"
    sys.exit()
key = sys.argv[1]

import subprocess
if subprocess.call("type xrdls", shell=True, 
        stdout=subprocess.PIPE, stderr=subprocess.PIPE) != 0:
    print "Error: Need xrdls from hep-tools"
    sys.exit()

ds = {'prodkey':key, 'samples':[]}
cmd = "xrdls %s"
samples = set(subprocess.check_output(cmd % "/store/group/CAT", shell=True).strip().split())
for s in samples:
    subSamples = set(subprocess.check_output(cmd % s, shell=True).strip().split())
    for ss in subSamples:
        timestamps = set(subprocess.check_output(cmd % ss, shell=True).strip().split())
        for ts in timestamps:
            #print ts
            if key != os.path.basename(ts).split('_')[0]: continue
            nset = set(subprocess.check_output(cmd % ts, shell=True).strip().split())
            for ns in nset:
                files = list(set(subprocess.check_output(cmd % ns, shell=True).strip().split()))
                files.sort()
                ds['samples'].append({'name':os.path.basename(s), 
                                      'subname':os.path.basename(ss),
                                      'files':files})

import json
f = open("samples.json", "w")
print>>f, json.dumps(ds)
