create-batch --jobName V1_SingleElectron_Run2016B  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleElectron_Run2016B.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleElectron_Run2016B --maxFiles 50
create-batch --jobName V1_SingleElectron_Run2016C  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleElectron_Run2016C.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleElectron_Run2016C --maxFiles 50
create-batch --jobName V1_SingleElectron_Run2016D  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleElectron_Run2016D.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleElectron_Run2016D --maxFiles 50
create-batch --jobName V1_SingleElectron_Run2016E  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleElectron_Run2016E.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleElectron_Run2016E --maxFiles 50
create-batch --jobName V1_SingleElectron_Run2016F  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleElectron_Run2016F.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleElectron_Run2016F --maxFiles 50
create-batch --jobName V1_SingleElectron_Run2016G  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleElectron_Run2016G.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleElectron_Run2016G --maxFiles 50
create-batch --jobName V1_SingleElectron_Run2016H_v2  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleElectron_Run2016H_v2.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleElectron_Run2016H_v2 --maxFiles 50
create-batch --jobName V1_SingleElectron_Run2016H_v3  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleElectron_Run2016H_v3.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleElectron_Run2016H_v3 --maxFiles 50
create-batch --jobName V1_SingleMuon_Run2016B  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleMuon_Run2016B.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleMuon_Run2016B --maxFiles 50
create-batch --jobName V1_SingleMuon_Run2016C  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleMuon_Run2016C.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleMuon_Run2016C --maxFiles 50
create-batch --jobName V1_SingleMuon_Run2016D  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleMuon_Run2016D.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleMuon_Run2016D --maxFiles 50
create-batch --jobName V1_SingleMuon_Run2016E  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleMuon_Run2016E.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleMuon_Run2016E --maxFiles 50
create-batch --jobName V1_SingleMuon_Run2016F  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleMuon_Run2016F.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleMuon_Run2016F --maxFiles 50
create-batch --jobName V1_SingleMuon_Run2016G  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleMuon_Run2016G.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleMuon_Run2016G --maxFiles 50
create-batch --jobName V1_SingleMuon_Run2016H_v2  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleMuon_Run2016H_v2.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleMuon_Run2016H_v2 --maxFiles 50
create-batch --jobName V1_SingleMuon_Run2016H_v3  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleMuon_Run2016H_v3.txt  --cfg topAnalyzer_RD_cfg.py --transferDest /store/user/tjkim/ntuples/hep2017/V1/SingleMuon_Run2016H_v3 --maxFiles 50

