#!/usr/bin/env python
import sys, os

# ///////////////////////////////////////////////////////////////////////////
# ///    Useage: dir/*.root ->(merge)-> results_merged/samplename.root    ///
# ///         to apply for all folders in pwd at once, enter 'all',       ///
# ///      otherwise only specific dir name where root files are in       ///
# ///////////////////////////////////////////////////////////////////////////

user_input = sys.argv[1]

if "results_merged" not in os.listdir(os.getcwd()):
    os.system("mkdir results_merged")
    print "'results_merged' has been created."

pwd = os.getcwd()+'/'
if user_input == "all":
    dir_list = [x for x in os.listdir(os.getcwd()) if (os.path.isdir(x) and x != "results_merged")]
else: dir_list = os.listdir(pwd+user_input)

failed_list = []
for d in dir_list:
    print pwd+d
    root_list = [x for x in os.listdir(pwd+d) if (("cattree" in x) and x.endswith(".root"))]
    file_names = ""
    for x in root_list:
        file_names += " %s/%s"%(pwd+d,x)
    if len(root_list) == 0:
        failed_list.append(d)
    else: os.system("hadd -f results_merged/%s.root"%d+file_names)

if len(failed_list) > 0:
    print
    print " ** What failed:    ", failed_list
    print



